In [140]:
import librosa
import librosa.display
import IPython.display as ipd
import matplotlib.pyplot as plt
import os
import pandas as pd
import numpy as np


# file='E:\MCA-2 Year\Main Project\dataset\Mayamalavagowla\Mmg.wav'
# audio, sample_rate = librosa.load(file)
# mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
# mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
# print("mfccs",mfccs_features)
# print("mfccs scaled",mfccs_scaled_features)


def features_extractor(file):
    audio, sample_rate = librosa.load(file)
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
    return mfccs_scaled_features


audio_path='E:\MCA-2 Year\Main Project\dataset'
extracted_features=[]
for dirpath, dirnames, filenames in os.walk(audio_path):
        for filename in filenames:
            if filename.endswith('.wav'):
                filepath=os.path.join(dirpath, filename)
                label=filepath.replace("E:\MCA-2 Year\Main Project\dataset", '').replace(filename,"").replace('\\','')
#                 print(filepath)
                mfccs=features_extractor(filepath)
                extracted_features.append([mfccs,label])
                

extracted_features_df=pd.DataFrame(extracted_features,columns=['feature','class'])
extracted_features_df

feature            class
0   [-257.00793, 143.21645, -63.392902, 45.306725,...  Mayamalavagowla
1   [-342.479, 121.16525, -28.796282, 44.39041, 14...  Mayamalavagowla
2   [-265.17584, 147.72835, -59.28968, 47.248676, ...  Mayamalavagowla
3   [-265.8661, 142.71452, -62.37273, 47.353455, 4...  Mayamalavagowla
4   [-270.8769, 146.13509, -59.109337, 46.9478, 1....  Mayamalavagowla
5   [-288.0216, 149.35812, -47.245678, 37.415783, ...  Mayamalavagowla
6   [-354.0573, 141.69968, 26.293093, 13.852002, -...  Mayamalavagowla
7   [-364.73254, 127.644356, 28.105154, 23.548061,...  Mayamalavagowla
8   [-358.08014, 125.53306, 32.00193, 22.871235, -...  Mayamalavagowla
9   [-358.75586, 140.48027, 27.321226, 9.683236, -...  Mayamalavagowla
10  [-329.88388, 132.13698, 24.247555, 18.087626, ...  Mayamalavagowla
11  [-301.8801, 77.61273, -43.964954, 6.8427114, -...  Mayamalavagowla
12  [-310.87204, 68.62663, -43.044067, 2.4750962, ...  Mayamalavagowla
13  [-302.76172, 74.42201, -47.095207, 5.852565, -...  Mayamalavagowla
14  [-197.08652, 81.49152, -48.00849, 36.93677, -1...          Mohanam
15  [-157.275, 95.572685, -55.988686, 30.901611, -...          Mohanam
16  [-178.47586, 78.64402, -35.6453, 20.774988, -1...          Mohanam
17  [-177.37201, 85.34112, -41.96415, 44.57123, -2...          Mohanam
18  [-172.45381, 82.0647, -43.0798, 23.08912, -7.3...          Mohanam
19  [-179.4202, 85.24829, -47.030994, 33.15376, -1...          Mohanam
20  [-308.3186, 102.52005, 13.691593, 20.561224, 1...          Mohanam
21  [-322.12534, 111.55545, 11.61951, 22.521864, 1...          Mohanam
22  [-330.14243, 118.97464, 11.84664, 25.165697, 7...          Mohanam
23  [-308.21133, 120.752266, 10.508814, 8.336225, ...          Mohanam
24  [-313.33838, 117.64787, 17.26717, 21.166502, 6...          Mohanam
25  [-311.86234, 116.409, 18.006712, 21.623466, 5....          Mohanam
26  [-310.63998, 125.96951, 15.492928, 19.149384, ...          Mohanam
27  [-169.67058, 96.48495, -66.12636, 43.346863, -...          Mohanam
28  [-155.1113, 56.9278, -52.016186, 39.760612, -2...          Mohanam
29  [-187.20172, 66.33403, -55.23273, 50.521683, -...          Mohanam
30  [-146.9628, 88.22245, -71.56997, 54.609814, -2...          Mohanam
31  [-323.00223, 95.03592, -51.75478, 6.7554083, -...          Mohanam
32  [-318.25247, 91.455414, -53.066055, 9.181376, ...          Mohanam
33  [-306.1751, 85.525764, -53.73121, 5.7814627, -...          Mohanam
34  [-353.21185, 119.59186, 24.895426, 25.061195, ...             Nata
35  [-334.3255, 98.12799, 24.627533, 23.619667, 4....             Nata
36  [-348.4952, 114.427605, 18.048315, 28.75373, 1...             Nata
37  [-169.45189, 79.42645, -64.57852, 58.774, -23....             Nata
38  [-177.13115, 85.14658, -64.99939, 53.943073, -...             Nata
39  [-355.67584, 125.1791, 18.90393, 27.903118, 2....             Nata
40  [-346.23193, 126.01379, 23.617458, 8.470036, -...             Nata
41  [-340.52994, 122.736664, 18.26399, 28.887371, ...             Nata
42  [-305.7635, 109.67052, 11.838475, 12.07011, -2...             Nata
43  [-298.6519, 112.5714, 8.725077, 7.9847956, -16...             Nata
44  [-355.63535, 116.9416, 28.144415, 26.806778, 6...             Nata
45  [-361.6717, 123.60966, 24.745937, 25.546164, 4...             Nata
46  [-351.00717, 120.8452, 15.672422, 35.007603, 9...             Nata
47  [-339.32803, 80.10002, -49.61237, 7.7818522, -...             Nata
48  [-349.57468, 83.12895, -50.074924, 9.405698, -...             Nata
49  [-347.8581, 81.89357, -48.651585, 9.595556, -1...             Nata

In [141]:
### Split the dataset into independent and dependent dataset
X=np.array(extracted_features_df['feature'].tolist())
y=np.array(extracted_features_df['class'].tolist())

In [142]:
### Label Encoding
###y=np.array(pd.get_dummies(y))
### Label Encoder
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
y=to_categorical(labelencoder.fit_transform(y))

In [195]:
# y

In [196]:
y.shape

(50, 3)

In [145]:
### Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [146]:
X_test

array([[-1.55111298e+02,  5.69277992e+01, -5.20161858e+01,
         3.97606125e+01, -2.30668774e+01,  1.15908365e+01,
        -1.62758541e+01,  2.09192133e+00, -6.49271345e+00,
         7.86300039e+00, -7.65429068e+00,  9.18413830e+00,
        -4.27179003e+00,  1.43066511e+01, -6.02619553e+00,
        -8.39855731e-01, -1.04500046e+01,  1.34619176e+00,
        -1.10813293e+01, -3.01489878e+00, -5.95804882e+00,
         1.55820203e+00, -1.28151524e+00,  1.67722836e+01,
         3.38041639e+00,  1.07513046e+01, -1.30613089e+00,
        -6.50946045e+00, -2.22519845e-01, -8.09815502e+00,
        -6.67637873e+00,  2.36736941e+00, -2.70435023e+00,
        -1.38272142e+00, -5.21208143e+00, -2.02848363e+00,
        -4.47473526e+00, -2.05537009e+00,  1.78530037e+00,
        -7.39262998e-01],
       [-3.01880096e+02,  7.76127319e+01, -4.39649544e+01,
         6.84271145e+00, -2.05005417e+01, -7.32769442e+00,
        -3.37500420e+01,  1.69511855e+00, -1.29970293e+01,
        -1.64801674e+01, -1.06

In [147]:
X_train

array([[-306.1751    ,   85.525764  ,  -53.73121   , ...,   -3.7955704 ,
          -3.726216  ,   -5.1125774 ],
       [-334.3255    ,   98.12799   ,   24.627533  , ...,   -2.796529  ,
          -5.6363254 ,   -2.1828659 ],
       [-310.63998   ,  125.96951   ,   15.492928  , ...,   -0.80832416,
          -1.2310495 ,    1.0921549 ],
       ...,
       [-257.00793   ,  143.21645   ,  -63.392902  , ...,   -0.94029754,
           2.4364781 ,    5.905712  ],
       [-339.32803   ,   80.10002   ,  -49.61237   , ...,   -6.2079253 ,
          -4.073739  ,    2.0393324 ],
       [-355.63535   ,  116.9416    ,   28.144415  , ...,   -2.1649451 ,
          -2.5114498 ,   -1.4634374 ]], dtype=float32)

In [148]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [149]:
y_train.shape

(40, 3)

In [150]:
y_test.shape

(10, 3)

In [151]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [152]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Flatten
from tensorflow.keras.optimizers import Adam
from sklearn import metrics

In [153]:
### No of classes
num_labels=y.shape[1]

In [154]:
num_labels

3

In [191]:
X_train.shape

(40, 40)

In [155]:
model=Sequential()
###first layer
model.add(Dense(100,input_shape=(40,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###second layer
model.add(Dense(200))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###third layer
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dropout(0.5))

###final layer
model.add(Dense(num_labels))
model.add(Activation('softmax'))

In [192]:
# model.summary()

In [157]:
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')

In [180]:
## Trianing my model
from tensorflow.keras.callbacks import ModelCheckpoint
from datetime import datetime 

num_epochs = 100
num_batch_size = 32

checkpointer = ModelCheckpoint(filepath='saved_models/audio_classification.hdf5', 
                               verbose=1, save_best_only=True)
start = datetime.now()

model.fit(X_train, y_train, batch_size=num_batch_size, epochs=num_epochs, validation_data=(X_test, y_test), callbacks=[checkpointer], verbose=1)


duration = datetime.now() - start
print("Training completed in time: ", duration)

Epoch 1/100
1/2 [==============>...............] - ETA: 0s - loss: 0.5185 - accuracy: 0.7188
Epoch 1: val_loss improved from inf to 0.57609, saving model to saved_models\audio_classification.hdf5
2/2 [==============================] - 0s 69ms/step - loss: 0.5194 - accuracy: 0.7750 - val_loss: 0.5761 - val_accuracy: 0.7000
Epoch 2/100
1/2 [==============>...............] - ETA: 0s - loss: 0.3753 - accuracy: 0.7812
Epoch 2: val_loss did not improve from 0.57609
2/2 [==============================] - 0s 22ms/step - loss: 0.4424 - accuracy: 0.7500 - val_loss: 0.5762 - val_accuracy: 0.7000
Epoch 3/100
1/2 [==============>...............] - ETA: 0s - loss: 0.6023 - accuracy: 0.7188
Epoch 3: val_loss improved from 0.57609 to 0.57461, saving model to saved_models\audio_classification.hdf5
2/2 [==============================] - 0s 40ms/step - loss: 0.5924 - accuracy: 0.7250 - val_loss: 0.5746 - val_accuracy: 0.7000
Epoch 4/100
1/2 [==============>...............] - ETA: 0s - loss: 0.5819 - accu

In [181]:
test_accuracy=model.evaluate(X_test,y_test,verbose=0)
print(test_accuracy[1])

0.8999999761581421


In [160]:
X_test[1]

array([-301.8801    ,   77.61273   ,  -43.964954  ,    6.8427114 ,
        -20.500542  ,   -7.3276944 ,  -33.750042  ,    1.6951185 ,
        -12.997029  ,  -16.480167  ,  -10.658158  ,   -7.267372  ,
          7.2302265 ,  -11.487329  ,   -1.4404794 ,   -1.6722199 ,
         -0.67388695,   -3.8953497 ,   -6.124888  ,    6.609958  ,
         -0.639382  ,   -6.7043495 ,  -11.424057  ,   -4.4399486 ,
          4.432351  ,    7.6369    ,    6.9158916 ,    4.337326  ,
         -3.3546386 ,   -7.624317  ,  -13.468939  ,   -9.058198  ,
          1.9282811 ,   -0.40594807,   -2.5053139 ,   -2.948418  ,
         -1.3994241 ,   -3.3526804 ,   -4.252746  ,   -1.0909921 ],
      dtype=float32)

In [182]:
predictions = (model.predict(X_test) > 0.5).astype("int32")
predictions

1/1 [==============================] - 0s 13ms/step


array([[0, 1, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]])

In [202]:
# filename="E:\MCA-2 Year\Main Project\dataset\Mayamalavagowla\Mmg.wav"
# audio, sample_rate = librosa.load(filename, res_type='kaiser_fast') 
# mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
# mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)
import librosa
# mfccs_scaled_features.shape
filename="C:/Users/Akhilraj/Downloads/Natta10M.wav"
audio, sample_rate = librosa.load(filename, res_type='kaiser_fast') 
mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)

# print(mfccs_scaled_features)
mfccs_scaled_features=mfccs_scaled_features.reshape(1,-1)
# print(mfccs_scaled_features)
# print(mfccs_scaled_features.shape)
predict_x=model.predict(mfccs_scaled_features) 
classes_x=np.argmax(predict_x,axis=1)
print(classes_x)
prediction_class = labelencoder.inverse_transform(classes_x) 
prediction_class

1/1 [==============================] - 0s 48ms/step
[2]


array(['Nata'], dtype='<U15')

In [163]:
# mfccs_scaled_features=mfccs_scaled_features.reshape(1,-1)
# print(mfccs_scaled_features)

In [164]:
# mfccs_scaled_features.shape
# mfccs_scaled_features
# X_train


In [165]:
# predicted_label=model.predict_class(mfccs_scaled_features)
# print(predicted_label)
# y_pred = model.predict(X_train)
# X_test.shape
# # 'y_pred' will be an array of predicted probabilities for each class in your output
# # to get the predicted class for each input, you can use the 'argmax' function to find the index of the maximum probability in each row
# y_pred_classes = y_pred.argmax(axis=-1)
# y_pred_classes
# a=labelencoder.inverse_transform(y_pred_classes)
# a